apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  namespace: distribuidos  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: luis486/auth-api:latest # Cambia a tu imagen y etiqueta específicas
        ports:
        - containerPort: 8000