apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api-deployment
  namespace: distribuidos  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
      - name: todos-api
        image: luis486/todos-api:latest # Cambia a tu imagen y etiqueta específicas
        ports:
        - containerPort: 8082