apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
  namespace: distribuidos  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: luis486/users-api:latest # Cambia a tu imagen y etiqueta específicas
        ports:
        - containerPort: 8083